### PR TITLE
Add image resize extension

### PR DESCRIPTION
**Pull request by wwayne**
Hi, sorry I only tested in my own repo, not sure if any CI works need to be added to this PR.
I also update the tailwind config so that the align-center can has an accurated position.

Result:

### CODE REVIEW

**Comment by arikchakma** [comment]
@wwayne Thanks for the PR, it's a nice feature. I'll check it out soon.

**Comment by wwayne** [comment]
@arikchakma thanks, no worries : )
I didn't check the coding format of the original project
Plz feel free to close this PR and add your own version if it would save your time

**Comment by arikchakma** [comment]
@wwayne No worries, The code seems fine to me. I'm just busy with some internal work, I'll check it and make some changes whenever I get time. Again Thanks for the PR man.

**Comment by arikchakma** [comment]
@wwayne Hey man, unfortunately, it's not working for me.
image

**Comment by arikchakma** [comment]
@wwayne What do you think if we use this [solution maybe](https://github.com/steven-tey/novel/blob/main/packages/core/src/ui/editor/extensions/image-resizer.tsx)?

**Comment by wwayne** [comment]
oh no : ( , I will take a try when I have time.
I'm not sure the solution you mentioned, but if it works then we can close this PR can use that one haha

**Comment by arikchakma** [comment]
Maybe it's because of the inline logo that I've? I'm not able to message you on twitter, mind pinging me there?

**Comment by arikchakma** [comment]
@wwayne Hey man I'm able to make it work. I'll make some tweaks and merge it, thanks, man.

**Comment by wwayne** [comment]
Cool good to know that : )

**Comment by wwayne** [comment]
I found after adding this image-resize extension, when dragging the image to another place, you can see the blurred image placeholder is in a incorrect position.
I will take a close look when i have time, and I was thinking maybe the solution you mentioned above https://github.com/steven-tey/novel/blob/main/packages/core/src/ui/editor/extensions/image-resizer.tsx is better, will take a try as well

**Comment by arikchakma** [comment]
But I don't see it, I've been fixing some from it. I'm almost done.

**Comment by arikchakma** [comment]
@wwayne I move this into #25 here, please let me know what you think. I've added some edge cases like preventing from scaling more than the container.

**Pull request closed without merging**
