### PR TITLE
Feat/i18n translations

### PR DESCRIPTION
**Pull request by BigDog1400**

### CODE REVIEW

**Comment by arikchakma** [comment]
I will check it asap, I'm a little bit busy with some internal work. Sorry for the delay man.

**Comment by arikchakma** [comment]
@BigDog1400 Can you please resolve the conflicts? I will have reviewed it, it looks good to me.

**Comment by BigDog1400** [comment]
@arikchakma sure! Give me a day

**Comment by arikchakma** [comment]
@BigDog1400 I'm closing this PR for now, there are so many conflicts right now. Maybe we can implement it in the future. I appreciate the work you have done. Thanks a lot.

**Pull request closed without merging**
