### PR TITLE
fix: blank iframe issue

### LINKED ISSUE #15: Preview Email button shows empty modal
To reproduce:

- open the [playground](https://maily.to/playground) and click on **Preview Email**

### PR DESCRIPTION
**Pull request by moogii**
## Description

fixes #15 
iframe [onLoad](https://stackoverflow.com/questions/12076494/onload-in-iframes-not-working-if-iframe-have-non-html-document-in-src-pdf-or-t/12190776#12190776) isn't working

### What

- set inner html in useeffect hook

### CODE REVIEW

**Comment by arikchakma** [comment]
Can you please add a before and after? I'm curious why `setTimeout` of `200ms`. Why not directly use the `useEffect` hooks?

**Comment by moogii** [comment]
**Before**
Screenshot 2023-11-02 at 21 45 04

**After**
Screenshot 2023-11-02 at 21 44 18

As for `setTimeout`, I have made mistake.

**Comment by arikchakma** [comment]
@moogii Thanks for the PR.

Can you please test it with other browsers, I've used this approach before. It wasn't working.

**Comment by moogii** [comment]
I read all comments on #15. Maily isn't working on Chrome (Version 118.0.5993.117 (Official Build) (arm64)) and Safari (Version 17.0 (19616.1.27.211.1)). Even after disabling extensions iframe was blank also I haven't installed any extensions on Safari. However it is working without issue on Brave though. After digging around I found that I frame is not consistent through browsers and OSs.

**Comment by arikchakma** [comment]
image

It's not working in Firefox.

**Comment by moogii** [comment]
Interesting. [Maily](https://maily.to/playground) preview is working properly in Firefox.
Now my solution is working in Firefox.

**Comment by arikchakma** [comment]
Check my changes, it will work now work on `Safari` and `Firefox` properly.

**Pull request merged**
